plentymarkets/plugin-elastic-export-rakuten-de

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed stock filter

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

added instance checks

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

1.1.2 price fix

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed instantiation

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

FIX images positions will now be correctly interpreted

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/ResultField/RakutenDE.php

fixed the sorting of the variation

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed ES cross shard variation bug

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/ResultField/RakutenDE.php

added the barcode mutator

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

RELEASE v1.1.11

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php
src/ResultField/RakutenDE.php

1.2.1 parent sku

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

1.2.2 parent decision fix

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed inventory management

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Api/Client.php
src/DataProvider/ElasticSearchDataProvider.php
src/Services/ItemUpdateService.php

optimized the stock update

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php
src/Helper/StockHelper.php
src/Services/ItemUpdateService.php

@plentymarkets/team-multichannel-koboldmaki 
@hschwab

added two fields to thhe stock update

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

@plentymarkets/team-multichannel-koboldmaki 
@hschwab

set the es shard size to 250 to avoid problems with the es token

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed an issue which caused duplicate entries of parent rows

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
meta/documents/user_guide_de.md
meta/documents/user_guide_en.md
plugin.json
src/Api/Client.php
src/Helper/StockHelper.php
src/Services/ItemUpdateService.php

Fix stock price update

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Api/Client.php
src/Services/ItemUpdateService.php

fix for product multi variant

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Api/Client.php
src/Generator/RakutenDE.php
src/Services/ItemUpdateService.php

1.2.14 batch logs

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Helper/StockHelper.php
src/Services/ItemUpdateService.php

reduced the delta time

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
meta/documents/user_guide_de.md
meta/documents/user_guide_en.md
plugin.json
src/Generator/RakutenDE.php
src/Helper/StockHelper.php

added new stock settings

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Api/Client.php
src/DataProvider/ElasticSearchDataProvider.php
src/Services/ItemUpdateService.php

1.3.1 sku status

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

@plentymarkets/team-multichannel-koboldmaki 
@hschwab

fix prefix and suffix

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Helper/PriceHelper.php
src/Services/ItemUpdateService.php

added a new price setting

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

@plentymarkets/team-multichannel-koboldmaki 
@snawratil

sku logic fix

---

config.json
meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
resources/lang/de/Config.properties
resources/lang/en/Config.properties

Multilingual plugin config

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
meta/documents/info_de.md
meta/documents/info_en.md
meta/documents/user_guide_de.md
meta/documents/user_guide_en.md
plugin.json

Updated user guide, added info tabs

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Helper/PriceHelper.php
src/Services/ItemUpdateService.php

Das Problem war das Updates abgelehnt wurden weil der reduzierte Preis nicht kleiner war als der eigentliche Preis. Das war aber unserer Preislogik in Rakuten geschuldet und sollte mit diesem Fix behoben sein.

fixed the price update for the reduced price

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

fixed the parent sku creation for parents without variations

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Crons/ItemUpdateCron.php
src/DataProvider/ElasticSearchDataProvider.php
src/ElasticExportRakutenDEServiceProvider.php
src/Generator/RakutenDE.php
src/Helper/SkuHelper.php
src/Helper/StockHelper.php
src/Services/ItemUpdateService.php

change performance improvement by reducing sku and stock queries

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Services/ItemUpdateService.php

fixed data transmission

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

CHANGE clear caches for categories, attributes and freetext fields

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Helper/StockHelper.php
src/Services/ItemUpdateService.php

fixed stock update

---

meta/documents/changelog_de.md
meta/documents/changelog_en.md
plugin.json
src/Generator/RakutenDE.php

FIX wrong vat rates exported
